name: CI

on:
  workflow_dispatch:

jobs:
  prepare_env:
    runs-on: ubuntu-latest
    name: Create new Hetzner Cloud instance for build
    steps:
      - uses: stonemaster/hetzner-github-runner@v2
        with:
          github-api-key: ${{ secrets.GH_API_KEY }}
          hetzner-api-key: ${{ secrets.HETZNER_API_KEY }}
          hetzner-instance-type: cx11

  build:
    runs-on: self-hosted
    needs: prepare_env
  
    steps:
      - uses: actions/checkout@v3
        with:
            path: 'meta-slint'
      - run: |
          sudo apt-get update
          sudo apt-get install chrpath diffstat lz4 locales build-essential wget readelf
          sudo locale-gen en_US.UTF-8
          sudo update-locale
      - run: |
          git clone -b kirkstone --single-branch git://git.yoctoproject.org/poky
          git clone -b kirkstone --single-branch git://git.openembedded.org/meta-openembedded
          git clone -b master --single-branch https://github.com/meta-rust/meta-rust.git
          git clone -b kirkstone --single-branch https://github.com/kraj/meta-clang.git          
      - run: |
          cd poky
          . oe-init-build-env
          bitbake-layers add-layer ../../meta-openembedded/meta-oe
          bitbake-layers add-layer ../../meta-rust
          bitbake-layers add-layer ../../meta-clang
          bitbake-layers add-layer ../../meta-slint
          echo 'PREFERRED_PROVIDER_virtual/kernel = "linux-dummy"' >> conf/local.conf
          echo 'MACHINE = "qemuarm64"' >> conf/local.conf
          echo 'CLANGSDK = "1"' >> conf/local.conf
          echo 'require ../meta-rust/conf/distro/include/rust_versions.inc' >> conf/local.conf
      - run: |
          cd poky
          . oe-init-build-env
          bitbake -c compile slint-cpp
